<script lang="ts">
import CourseAudio from "./CourseAudio.svelte";
import type {CourseAction,CourseActionResult,PublicCourseLesson,CourseProgress,CourseSentence} from "../../types/course";
let {lesson,progress,feedback,busy,act,startIndex=0,inspected=false,onSupportUsed,onPosition}:{lesson:PublicCourseLesson;progress:CourseProgress;feedback:Record<string,NonNullable<CourseActionResult["feedback"]>>;busy:boolean;act:(a:CourseAction)=>Promise<CourseActionResult|undefined>;startIndex?:number;inspected?:boolean;onSupportUsed:()=>void;onPosition:(index:number)=>void}=$props();
let exerciseIndex=$state(0);
$effect(()=>{exerciseIndex=startIndex;});
$effect(()=>{onPosition(exerciseIndex);});
let currentExercise=$derived(lesson.exercises[exerciseIndex]);
let language=$derived(lesson.language);let isArabic=$derived(language==="ar-EG");
let showTransliteration=$state(false);let showEnglish=$state(false);let transliterationUsed=$state(false);$effect(()=>{if(showTransliteration){transliterationUsed=true;onSupportUsed();}});
let drafts=$state<Record<string,string>>({});let tokenSelections=$state<Record<string,number[]>>({});let matches=$state<Record<string,Record<string,string>>>({});
let answered=$derived(Object.values(progress.exercises).filter(e=>e.attempts.length).length);
const pending=new Map<string,{answer:string;id:string}>();
function chooseToken(index:number){const id=currentExercise.id;tokenSelections={...tokenSelections,[id]:[...(tokenSelections[id]??[]),index]};drafts={...drafts,[id]:tokenSelections[id].map(i=>currentExercise.choices![i]).join(" ")};}
function responseText(answer:string){if(currentExercise.type!=="matching")return answer;try{const pairs=JSON.parse(answer) as Record<string,string>;return (currentExercise.matchingPairs??[]).map(p=>`${p.text}: ${pairs[p.id]??""}`).join("; ");}catch{return answer;}}
async function submit(){const answer=drafts[currentExercise.id];if(!answer?.trim())return;const prior=pending.get(currentExercise.id);const id=prior?.answer===answer?prior.id:crypto.randomUUID();pending.set(currentExercise.id,{answer,id});await act({type:"answer",exerciseId:currentExercise.id,attemptId:id,answer,transliterationVisible:isArabic&&showTransliteration,supportUsed:inspected||transliterationUsed,evidenceVersion:2});}
</script>
{#snippet sentence(item:CourseSentence)}<div class="sentence"><p class="target" lang={language} dir={isArabic?"rtl":"ltr"}>{item.text}</p><CourseAudio {language} text={item.text} hideMissing/>{#if item.transliteration&&showTransliteration}<p class="transliteration" dir="ltr">{item.transliteration}</p>{/if}<p class="translation">{item.english}</p></div>{/snippet}
<div class="practice-tools"><label>Question <select aria-label="Question" value={exerciseIndex} onchange={e=>exerciseIndex=Number(e.currentTarget.value)}>{#each lesson.exercises as exercise,i}<option value={i}>{i+1} / {lesson.exercises.length} · {{choice:"Choose",recall:"Write",order:"Order",matching:"Match","self-check":"Compare"}[exercise.type]}{progress.exercises[exercise.id]?.attempts.length?" · attempted":""}</option>{/each}</select></label>{#if isArabic}<label><input type="checkbox" bind:checked={showTransliteration}/> Transliteration support</label>{/if}</div>
        <section class="quiz" aria-label="Practice question"><h2>{currentExercise.prompt}</h2>
          {#if currentExercise.promptAtom}<div class="sentence"><p class="target" dir={isArabic ? "rtl" : "ltr"}>{currentExercise.promptAtom.text}</p><CourseAudio {language} text={currentExercise.promptAtom.text} hideMissing/>{#if showTransliteration && currentExercise.promptAtom.transliteration}<p class="transliteration">{currentExercise.promptAtom.transliteration}</p>{/if}{#if feedback[currentExercise.id]?.promptEnglish}<p class="translation">{feedback[currentExercise.id].promptEnglish}</p>{/if}</div>{/if}
          {#each currentExercise.supportAtoms ?? [] as support}<div class="teaching-note">{@render sentence(support)}</div>{/each}
          {#if currentExercise.type === "matching"}<div class="matching-pairs">{#each currentExercise.matchingPairs ?? [] as pair}<label class="matching-row"><span><b dir="auto">{pair.text}</b><CourseAudio {language} text={pair.text} hideMissing/>{#if progress.exercises[currentExercise.id]?.attempts.at(-1)?.pairResults}{@const pairResult = progress.exercises[currentExercise.id].attempts.at(-1)?.pairResults?.find(p => p.id === pair.id)}<small>{pairResult?.correct ? "Matched" : "Try this pair again"}</small>{/if}{#if showTransliteration && pair.transliteration}<small class="transliteration">{pair.transliteration}</small>{/if}</span><select aria-label={`Meaning for ${pair.text}`} value={matches[currentExercise.id]?.[pair.id] ?? ""} disabled={busy} onchange={event => { const id=currentExercise!.id; matches={...matches,[id]:{...matches[id],[pair.id]:event.currentTarget.value}}; drafts={...drafts,[id]:Object.keys(matches[id]).length===currentExercise!.matchingPairs!.length && Object.values(matches[id]).every(Boolean) ? JSON.stringify(matches[id]) : ""}; }}><option value="">Choose a meaning</option>{#each currentExercise.choices ?? [] as meaning}<option value={meaning}>{meaning}</option>{/each}</select></label>{/each}</div>
          {:else if currentExercise.type === "choice"}<div class="choices">{#each currentExercise.choices ?? [] as choice, index}<button class:selected={drafts[currentExercise.id] === choice} aria-pressed={drafts[currentExercise.id] === choice} disabled={busy} onclick={() => drafts = { ...drafts, [currentExercise.id]: choice }}><span class="option-index">{String.fromCharCode(65 + index)}</span><span><b dir="auto">{choice}</b>{#if currentExercise.choiceSupport?.[choice]?.transliteration && showTransliteration}<small>{currentExercise.choiceSupport[choice].transliteration}</small>{/if}{#if (feedback[currentExercise.id]?.choiceSupport ?? currentExercise.choiceSupport)?.[choice]?.english}<small>{(feedback[currentExercise.id]?.choiceSupport ?? currentExercise.choiceSupport)?.[choice]?.english}</small>{/if}</span></button>{#if currentExercise.choiceSupport?.[choice]}<CourseAudio {language} text={choice} hideMissing/>{/if}{/each}</div>
          {:else if currentExercise.type === "order"}<div class="answer-built" dir={isArabic ? "rtl" : "ltr"}>{drafts[currentExercise.id] || "Select the words below"}</div><div class="tokens">{#each currentExercise.choices ?? [] as token, i}<button disabled={busy || tokenSelections[currentExercise.id]?.includes(i)} onclick={() => chooseToken(i)}>{token}{#if showTransliteration && currentExercise.choiceSupport?.[token]?.transliteration}<small>{currentExercise.choiceSupport[token].transliteration}</small>{/if}</button><CourseAudio {language} text={token} hideMissing/>{/each}</div><button class="text-button" onclick={() => { tokenSelections = { ...tokenSelections, [currentExercise!.id]: [] }; drafts = { ...drafts, [currentExercise!.id]: "" }; }}>Clear sentence</button>
          {:else if currentExercise.type === "self-check"}<label class="answer-label" for="self-check-answer">Your response</label><textarea id="self-check-answer" class="answer-input" rows="4" dir="auto" value={drafts[currentExercise.id] ?? ""} oninput={event => drafts = { ...drafts, [currentExercise!.id]: event.currentTarget.value }} placeholder="Write your response, then compare it with the model and rubric."></textarea>
          {:else}<label class="answer-label" for="recall-answer">Your answer</label><input id="recall-answer" class="answer-input" dir="auto" autocomplete="off" value={drafts[currentExercise.id] ?? ""} oninput={event => drafts = { ...drafts, [currentExercise!.id]: event.currentTarget.value }} onkeydown={event => { if (event.key === "Enter") void submit(); }} placeholder={isArabic ? "Type Arabic (or transliteration when requested)" : "Type your answer…"} />{/if}
          <div class="quiz-actions"><button class="primary" disabled={busy || !drafts[currentExercise.id]?.trim()} onclick={submit}>{progress.exercises[currentExercise.id]?.attempts.length ? "Check practice answer" : "Check answer"}</button><button class="text-button" disabled={busy} onclick={() => act({ type: "hint", exerciseId: currentExercise!.id })}>Give me a hint</button><button class="text-button" disabled={busy} onclick={() => act({ type: "reveal", exerciseId: currentExercise!.id })}>Show answer</button></div>
          {#if feedback[currentExercise.id]}{@const result = feedback[currentExercise.id]}<div class="feedback" class:correct={result.correct === true} role="status">{#if progress.exercises[currentExercise.id]?.attempts.length}<p class="your-answer">Your response: <bdi>{responseText(progress.exercises[currentExercise.id].attempts.at(-1)?.answer??"")}</bdi></p>{/if}<strong>{result.correct == null ? "Compare" : result.correct ? "Correct" : "Try again"}</strong>{#if result.answerAtoms?.length}{#each result.answerAtoms as atom}{@render sentence(atom)}{/each}{:else if result.answer}<p class="feedback-answer" dir="auto">{result.answer}</p>{#if language==="hu"||/[\u0600-\u06ff]/u.test(result.answer)}<CourseAudio {language} text={result.answer} hideMissing/>{/if}{/if}{#if result.text}<p>{result.text}</p>{/if}{#if result.rubricText}<p class="rubric">{result.rubricText}</p>{/if}
          {#if currentExercise.type === "self-check" && progress.exercises[currentExercise.id]?.attempts.length}<div class="self-assessment"><p>After comparing, how did your response meet the rubric?</p>{#each [["again","Needs another try"],["close","Partly meets it"],["met","Meets the rubric"]] as option}<button class="secondary" disabled={busy} aria-pressed={progress.exercises[currentExercise.id].attempts.at(-1)?.selfAssessment === option[0]} onclick={() => act({type:"self-assess",exerciseId:currentExercise!.id,assessment:option[0] as "again"|"close"|"met"})}>{option[1]}</button>{/each}</div>{/if}</div>{/if}
          <div class="question-nav"><button class="secondary" disabled={exerciseIndex === 0 || busy} onclick={() => exerciseIndex--}>Previous</button><button class="secondary" disabled={exerciseIndex === lesson.exercises.length - 1 || busy} onclick={() => exerciseIndex++}>Next question</button></div>
        </section>
<style>
.practice-tools,.quiz-actions,.question-nav{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.practice-tools{padding:12px 0;border-bottom:1px solid #d4d8d1}.practice-tools label{display:flex;align-items:center;gap:8px}.quiz h2{font-size:22px;line-height:1.45;font-weight:600;margin:8px 0 20px;white-space:pre-line}.sentence{margin:12px 0}.target{font-size:22px;line-height:1.7}.target[dir=rtl]{font-size:27px;font-family:Tahoma,sans-serif}.transliteration,.translation{font-size:16px;color:#545e57;margin-top:4px}.choices{display:grid;gap:8px}.choices button{display:flex;gap:14px;text-align:left;align-items:center;padding:12px;background:white;border:1px solid #b2bcb5}.choices button.selected{background:#e7f0e9;border-color:#245c44}.choices b{font-weight:400;font-size:21px;line-height:1.6}.choices small,.tokens small{display:block;font-size:14px;margin-top:4px}.option-index{color:#545e57}.answer-label{display:block;margin-bottom:8px}.answer-input{width:100%;padding:12px;border:1px solid #84998c;border-radius:3px;background:#fff;font-size:20px}.answer-built{min-height:60px;padding:12px;border-bottom:1px solid #84998c;font-size:22px}.tokens{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.tokens button{background:white;border:1px solid #b2bcb5;padding:8px 12px;font-size:18px}.quiz-actions{justify-content:flex-start;margin-top:20px}.primary,.secondary,select{padding:9px 12px;border:1px solid #84998c;border-radius:3px;background:white;color:#234b38;font:inherit;min-height:44px}.primary{background:#245c44;color:white;border-color:#245c44}.text-button{background:none;border:0;color:#245c44;text-decoration:underline;text-underline-offset:3px;min-height:44px;font:inherit}.feedback{padding:16px;margin:20px 0;background:#f2efe5;border:1px solid #d7ccb4;line-height:1.6}.feedback.correct{background:#edf3ed;border-color:#b9ccb9}.feedback>p{margin:8px 0}.feedback .feedback-answer{font-size:22px;white-space:pre-line}.your-answer{overflow-wrap:anywhere}.question-nav{border-top:1px solid #d4d8d1;padding-top:20px;margin-top:24px}.matching-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;align-items:center;margin:16px 0}.matching-row b{font-size:21px}.matching-row small{display:block;font-size:14px}.matching-row select{width:100%;min-width:0}.self-assessment{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.self-assessment p{width:100%}.self-assessment [aria-pressed=true]{background:#d9e9dd}.teaching-note{padding:12px;background:#f1f3ed}.rubric{white-space:pre-line}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid #245c44;outline-offset:3px}
@media(max-width:600px){.quiz h2{font-size:20px}.quiz-actions{gap:8px}.matching-row{gap:8px}.practice-tools{align-items:flex-start}}
</style>