import {chromium,expect} from "@playwright/test";
import {loadCourseCatalog} from "../../src/services/course/catalog.ts";
const base=Bun.argv[2]??"http://localhost:8792";
const lessons=await loadCourseCatalog();const browser=await chromium.launch({channel:"chrome",headless:true});
for(const language of ["hu","ar-EG"]){const context=await browser.newContext();const page=await context.newPage();const lesson=lessons.find(l=>l.language===language&&l.exercises.some(e=>e.type==="matching")&&l.exercises.some(e=>e.type==="self-check"))!;
await page.goto(`${base}/#/course/${language}/${lesson.id}`);await page.getByRole("button",{name:"Practise",exact:true}).click();
for(const type of ["matching","order","self-check"]){const index=lesson.exercises.findIndex(e=>e.type===type);if(index<0)continue;const e=lesson.exercises[index];await page.getByLabel("Question",{exact:true}).selectOption(String(index));
if(type==="matching"){for(const pair of e.matchingPairs??[])await page.getByLabel(`Meaning for ${pair.text}`,{exact:true}).selectOption(pair.answer);}
else if(type==="order"){await page.locator(".tokens button").first().click();await page.getByRole("button",{name:"Clear sentence",exact:true}).click();await expect(page.locator(".answer-built")).toHaveText("Select the words below");for(let i=0;i<(e.choices?.length??0);i++)await page.locator(".tokens button").nth(i).click();}
else await page.getByLabel("Your response",{exact:true}).fill("My own practice response");
await page.getByRole("button",{name:/^Check (practice )?answer$/}).click();await expect(page.locator(".feedback")).toBeVisible();await expect(page.getByLabel("Question",{exact:true})).toHaveValue(String(index));
if(type==="self-check"){await page.getByRole("button",{name:"Partly meets it",exact:true}).click();await expect(page.getByRole("button",{name:"Partly meets it",exact:true})).toHaveAttribute("aria-pressed","true");}
const attempt=await page.evaluate(({id,e})=>JSON.parse(localStorage.getItem(`langouste-course-local:v1:${id}`)!).exercises[e].attempts.at(-1),{id:lesson.id,e:e.id});expect(attempt.scored).toBe(false);if(type==="matching")expect(attempt.pairResults.every((p:{correct:boolean})=>p.correct)).toBe(true);if(type==="self-check"){expect(attempt.correct).toBe(null);expect(attempt.selfAssessment).toBe("close");}
}
// Transliteration shown then hidden and reloaded remains supported evidence.
if(language==="ar-EG"){const i=lesson.exercises.findIndex(e=>e.type==="recall");await page.getByLabel("Question",{exact:true}).selectOption(String(i));await page.getByLabel("Transliteration support",{exact:true}).check();await page.getByLabel("Transliteration support",{exact:true}).uncheck();await page.reload();await expect(page.getByLabel("Question",{exact:true})).toHaveValue(String(i));await page.getByLabel("Your answer",{exact:true}).fill(lesson.exercises[i].acceptedAnswers[0]);await page.getByRole("button",{name:"Check answer",exact:true}).click();await expect(page.locator(".feedback")).toBeVisible();const a=await page.evaluate(({id,e})=>JSON.parse(localStorage.getItem(`langouste-course-local:v1:${id}`)!).exercises[e].attempts.at(-1),{id:lesson.id,e:lesson.exercises[i].id});expect(a.supportUsed).toBe(true);expect(a.scored).toBe(false);}
await page.getByRole("button",{name:"Read",exact:true}).click();await page.getByLabel("Reading passage").selectOption("1");await page.reload();await expect(page.getByLabel("Reading passage")).toHaveValue("1");
const trigger=page.locator(".word-strip button").first();await trigger.click();await page.locator(".inspector .dict-word").first().press("Enter");await page.keyboard.press("Escape");await expect(trigger).toBeFocused();
await page.keyboard.press("Tab");const before=page.url();await page.locator(".skip").focus();await page.keyboard.press("Enter");expect(page.url()).toBe(before);await expect(page.locator("#study-content")).toBeFocused();
await page.goto(`${base}/#/course/${language}/reference`);await expect(page.locator(".reference-list details").first()).toBeVisible();const other=lessons.find(l=>l.language===language&&l.id!==lesson.id&&l.exercises.some(e=>e.type==="recall"))!;await page.goto(`${base}/#/course/${language}/${other.id}`);await page.getByRole("button",{name:"Practise",exact:true}).click();const recallIndex=other.exercises.findIndex(e=>e.type==="recall");await page.getByLabel("Question",{exact:true}).selectOption(String(recallIndex));await page.getByLabel("Your answer",{exact:true}).fill(other.exercises[recallIndex].acceptedAnswers[0]);await page.getByRole("button",{name:"Check answer",exact:true}).click();await expect(page.locator(".feedback")).toBeVisible();const supported=await page.evaluate(({id,e})=>JSON.parse(localStorage.getItem(`langouste-course-local:v1:${id}`)!).exercises[e].attempts.at(-1),{id:other.id,e:other.exercises[recallIndex].id});expect(supported.scored).toBe(false);expect(supported.supportUsed).toBe(true);
console.log(`PASS ${language}: matching, order/reset, self-assessment, no auto-advance, exact passage/question resume, skip link`);await context.close();}
await browser.close();
