export interface IpaRule {
  pattern: string;
  ipa: string;
}

export interface IpaRuleSet {
  language: string;
  stress?: "initial";
  rules: IpaRule[];
}

export const ipaRuleSets: Record<string, IpaRuleSet> = {
  de: {
    language: "de",
    rules: [
      { pattern: "tsch", ipa: "tʃ" },
      { pattern: "sch", ipa: "ʃ" },
      { pattern: "ch", ipa: "ç" },
      { pattern: "ck", ipa: "k" },
      { pattern: "ph", ipa: "f" },
      { pattern: "th", ipa: "t" },
      { pattern: "sp", ipa: "ʃp" },
      { pattern: "st", ipa: "ʃt" },
      { pattern: "ei", ipa: "aɪ" },
      { pattern: "ie", ipa: "iː" },
      { pattern: "eu", ipa: "ɔʏ" },
      { pattern: "äu", ipa: "ɔʏ" },
      { pattern: "au", ipa: "aʊ" },
      { pattern: "qu", ipa: "kv" },
      { pattern: "ä", ipa: "ɛ" },
      { pattern: "ö", ipa: "ø" },
      { pattern: "ü", ipa: "yː" },
      { pattern: "ß", ipa: "s" },
      { pattern: "aa", ipa: "aː" },
      { pattern: "ee", ipa: "eː" },
      { pattern: "oo", ipa: "oː" },
      { pattern: "a", ipa: "a" },
      { pattern: "e", ipa: "ə" },
      { pattern: "i", ipa: "ɪ" },
      { pattern: "o", ipa: "ɔ" },
      { pattern: "u", ipa: "ʊ" },
      { pattern: "y", ipa: "ʏ" },
      { pattern: "b", ipa: "b" },
      { pattern: "c", ipa: "k" },
      { pattern: "d", ipa: "d" },
      { pattern: "f", ipa: "f" },
      { pattern: "g", ipa: "ɡ" },
      { pattern: "h", ipa: "h" },
      { pattern: "j", ipa: "j" },
      { pattern: "k", ipa: "k" },
      { pattern: "l", ipa: "l" },
      { pattern: "m", ipa: "m" },
      { pattern: "n", ipa: "n" },
      { pattern: "p", ipa: "p" },
      { pattern: "r", ipa: "ʁ" },
      { pattern: "s", ipa: "z" },
      { pattern: "t", ipa: "t" },
      { pattern: "v", ipa: "f" },
      { pattern: "w", ipa: "v" },
      { pattern: "x", ipa: "ks" },
      { pattern: "z", ipa: "ts" },
    ],
  },
  hu: {
    language: "hu",
    stress: "initial",
    rules: [
      { pattern: "dzs", ipa: "dʒ" },
      { pattern: "cs", ipa: "tʃ" },
      { pattern: "dz", ipa: "dz" },
      { pattern: "gy", ipa: "ɟ" },
      { pattern: "ly", ipa: "j" },
      { pattern: "ny", ipa: "ɲ" },
      { pattern: "sz", ipa: "s" },
      { pattern: "ty", ipa: "c" },
      { pattern: "zs", ipa: "ʒ" },
      { pattern: "á", ipa: "aː" },
      { pattern: "é", ipa: "eː" },
      { pattern: "í", ipa: "iː" },
      { pattern: "ó", ipa: "oː" },
      { pattern: "ö", ipa: "ø" },
      { pattern: "ő", ipa: "øː" },
      { pattern: "ú", ipa: "uː" },
      { pattern: "ü", ipa: "y" },
      { pattern: "ű", ipa: "yː" },
      { pattern: "a", ipa: "ɒ" },
      { pattern: "e", ipa: "ɛ" },
      { pattern: "i", ipa: "i" },
      { pattern: "o", ipa: "o" },
      { pattern: "u", ipa: "u" },
      { pattern: "b", ipa: "b" },
      { pattern: "c", ipa: "ts" },
      { pattern: "d", ipa: "d" },
      { pattern: "f", ipa: "f" },
      { pattern: "g", ipa: "ɡ" },
      { pattern: "h", ipa: "h" },
      { pattern: "j", ipa: "j" },
      { pattern: "k", ipa: "k" },
      { pattern: "l", ipa: "l" },
      { pattern: "m", ipa: "m" },
      { pattern: "n", ipa: "n" },
      { pattern: "p", ipa: "p" },
      { pattern: "r", ipa: "r" },
      { pattern: "s", ipa: "ʃ" },
      { pattern: "t", ipa: "t" },
      { pattern: "v", ipa: "v" },
      { pattern: "z", ipa: "z" },
    ],
  },
  it: {
    language: "it",
    rules: [
      { pattern: "gli", ipa: "ʎi" },
      { pattern: "gn", ipa: "ɲ" },
      { pattern: "sch", ipa: "sk" },
      { pattern: "sci", ipa: "ʃi" },
      { pattern: "sce", ipa: "ʃe" },
      { pattern: "sc", ipa: "sk" },
      { pattern: "chi", ipa: "ki" },
      { pattern: "che", ipa: "ke" },
      { pattern: "ch", ipa: "k" },
      { pattern: "ghi", ipa: "ɡi" },
      { pattern: "ghe", ipa: "ɡe" },
      { pattern: "gh", ipa: "ɡ" },
      { pattern: "ci", ipa: "tʃi" },
      { pattern: "ce", ipa: "tʃe" },
      { pattern: "gi", ipa: "dʒi" },
      { pattern: "ge", ipa: "dʒe" },
      { pattern: "zz", ipa: "tts" },
      { pattern: "ss", ipa: "ss" },
      { pattern: "rr", ipa: "rr" },
      { pattern: "ll", ipa: "ll" },
      { pattern: "cc", ipa: "kk" },
      { pattern: "tt", ipa: "tt" },
      { pattern: "pp", ipa: "pp" },
      { pattern: "mm", ipa: "mm" },
      { pattern: "nn", ipa: "nn" },
      { pattern: "bb", ipa: "bb" },
      { pattern: "dd", ipa: "dd" },
      { pattern: "ff", ipa: "ff" },
      { pattern: "gg", ipa: "ɡɡ" },
      { pattern: "à", ipa: "a" },
      { pattern: "è", ipa: "ɛ" },
      { pattern: "é", ipa: "e" },
      { pattern: "ì", ipa: "i" },
      { pattern: "ò", ipa: "ɔ" },
      { pattern: "ó", ipa: "o" },
      { pattern: "ù", ipa: "u" },
      { pattern: "a", ipa: "a" },
      { pattern: "e", ipa: "e" },
      { pattern: "i", ipa: "i" },
      { pattern: "o", ipa: "o" },
      { pattern: "u", ipa: "u" },
      { pattern: "b", ipa: "b" },
      { pattern: "c", ipa: "k" },
      { pattern: "d", ipa: "d" },
      { pattern: "f", ipa: "f" },
      { pattern: "g", ipa: "ɡ" },
      { pattern: "h", ipa: "" },
      { pattern: "j", ipa: "j" },
      { pattern: "k", ipa: "k" },
      { pattern: "l", ipa: "l" },
      { pattern: "m", ipa: "m" },
      { pattern: "n", ipa: "n" },
      { pattern: "p", ipa: "p" },
      { pattern: "q", ipa: "k" },
      { pattern: "r", ipa: "r" },
      { pattern: "s", ipa: "s" },
      { pattern: "t", ipa: "t" },
      { pattern: "v", ipa: "v" },
      { pattern: "w", ipa: "w" },
      { pattern: "x", ipa: "ks" },
      { pattern: "y", ipa: "i" },
      { pattern: "z", ipa: "ts" },
    ],
  },
  tr: {
    language: "tr",
    rules: [
      { pattern: "â", ipa: "aː" },
      { pattern: "î", ipa: "iː" },
      { pattern: "û", ipa: "uː" },
      { pattern: "a", ipa: "a" },
      { pattern: "e", ipa: "e" },
      { pattern: "ı", ipa: "ɯ" },
      { pattern: "i", ipa: "i" },
      { pattern: "o", ipa: "o" },
      { pattern: "ö", ipa: "ø" },
      { pattern: "u", ipa: "u" },
      { pattern: "ü", ipa: "y" },
      { pattern: "b", ipa: "b" },
      { pattern: "c", ipa: "dʒ" },
      { pattern: "ç", ipa: "tʃ" },
      { pattern: "d", ipa: "d" },
      { pattern: "f", ipa: "f" },
      { pattern: "g", ipa: "ɡ" },
      { pattern: "ğ", ipa: "" },
      { pattern: "h", ipa: "h" },
      { pattern: "j", ipa: "ʒ" },
      { pattern: "k", ipa: "k" },
      { pattern: "l", ipa: "l" },
      { pattern: "m", ipa: "m" },
      { pattern: "n", ipa: "n" },
      { pattern: "p", ipa: "p" },
      { pattern: "r", ipa: "ɾ" },
      { pattern: "s", ipa: "s" },
      { pattern: "ş", ipa: "ʃ" },
      { pattern: "t", ipa: "t" },
      { pattern: "v", ipa: "v" },
      { pattern: "y", ipa: "j" },
      { pattern: "z", ipa: "z" },
    ],
  },
};
